import { GraphQLScalarType } from 'graphql';
export declare const Int32: GraphQLScalarType;
export declare const Int64: GraphQLScalarType;
export declare const Uint32: GraphQLScalarType;
export declare const Sint32: GraphQLScalarType;
export declare const Fixed32: GraphQLScalarType;
export declare const Sfixed32: GraphQLScalarType;
export declare const Uint64: GraphQLScalarType;
export declare const Sint64: GraphQLScalarType;
export declare const Fixed64: GraphQLScalarType;
export declare const Sfixed64: GraphQLScalarType;
export declare const Bool: GraphQLScalarType;
export declare const Bytes: GraphQLScalarType;
export declare const Empty: GraphQLScalarType;
export declare const Error: GraphQLScalarType;
